
spring:
  security:
    user:
      name: admin # default user name, default value is user
      password: admin # default password, default value is randomly generated

  flyway:
    url: jdbc:mysql://localhost:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    user: root
    password: root

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG

server:
  port: 8081
